provider.name=Pluto
provider.id=200
#xmltv.files=/unraid/appdata/xmltvdata/PlutoTV_NEW_epgdata.xml
xmltv.files=http://192.168.10.175:8087/epg.xml
xmltv.profile=Pluto

# Lineup values below override xmltv_Pluto.profile and common.properties.
sagetv.show.Icon=true
