provider.name=OTA_Local
provider.id=2
xmltv.files=/unraid/appdata/xmltvdata/guide.xml
xmltv.profile=OTA_Local

# Provider values override xmltv_OTA_Local.profile and common.properties.
sagetv.show.Icon=true
