provider.name=nyplayer
provider.id=300
xmltv.files=/unraid/appdata/xmltvdata/nyplayer_epgdata.xml
xmltv.profile=IPTV

# This feed uses a different display-name order than the generic IPTV profile.
xmltv.channel.display-name.ShortNameIndex=2
xmltv.channel.display-name.LongNameIndex=1
#channel OR display-name OR <custom_tag_name> OR Comment Out for  AUTO
xmltv.channel.NumberTag=lcn
#The tag occurance when  xmltv.channel.NumberTag=display-name
xmltv.channel.NumberTagIndex=1
#RegEx Group 0 to find Channel Number (must escape backslash)
#Comment out and if no filtering is require
#Examples
#(?<=I)(.*)(?=\\.\\d+)	Group 0=Between I and second period if digit after <=2 
#^([^ ]+) 				Group 0=Everything before first space
#xmltv.channel.NumberTagRegEx=^([^ ]+)

xmltv.programme.episode-num.system.showID_Value=tms
sagetv.show.Icon=true
